# Generated by Django 2.0.3 on 2018-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='review',
        ),
        migrations.AlterField(
            model_name='address',
            name='house_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='shop_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
